import('./jquery.js')

// import ('./header_sites_handler.js')
import ('./mobile_menu_handler.js')
import ('./jquery.min.js')
// import ('./header_phones_handler.js')
import ('./header_lang_handler.js')
import ('./on_top_handler.js')
// import ('./header_mobile_ico_handler.js')
import ('./captcha-validator.js')
import ('./popup_write_us.js')
import ('./popup_login.js')
